### ISSUE TITLE
Emails scroll horizontally in Inbox on iPhone 5-sized phone

### ISSUE THREAD

**Issue by bernerdschaefer** [thoughtbot/constable#154]
The new email template is looking great so far, and works much better on the phone!

It's still a _bit_ too wide to fit on my screen, though, and requires some scrolling around. I'd love if everything fit on the screen! I also realize I might be the only person with a screen this size, and recognize it may not be able to accommodate all of us.

---

![img_1344](https://cloud.githubusercontent.com/assets/193/12854621/85d09198-cbef-11e5-85a6-f90544b13bf8.PNG)

**Comment by brimatteng** [comment]
I don't think this is still a problem, if anyone's following this. Feel free to reopen if you have this problem
