### ISSUE TITLE
Make the "Subscribe/Unsubscribe" button more clear

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/constable#248]
Starting from https://thoughtbot.slack.com/archives/nyc/p1462393370001295

Specifically: https://thoughtbot.slack.com/archives/nyc/p1462393470001299

I think we should change the wording to "subscribe to comments" or "subscribe to thread" or something along those lines. We may also want to reposition it, but I think changing the wording is a good start

**Comment by mborsare** [comment]
This was addressed with: https://github.com/thoughtbot/constable/commit/29f44b5508874407e1f4626aaf2c601bc07e2a5f. So I'm closing this issue.
