### ISSUE TITLE
Create a demo site so people can try it out

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/constable#357]
We could set up a demo subdomain that allows anyone with an @gmail.com domain. We'd have to disable email sending, but that shouldn't be hard. We could just use the LocalAdapter or make an invalid Mandrill key.

I think this is important so that people can give it a try without having to go through all the setup themselves first. It's also something people could link to and show to their friends bosses when pitching how fast and nice apps can be using Phoenix

**Comment by Nikkau** [comment]
Hi,

https://constable-demo.herokuapp.com/ existes but is restricted to thoughtbot email address.

**Comment by paulcsmith** [comment]
@Nikkau Hmm that's strange. Others have been able to get on and try it out with their gmail.com account. Can you try that again with an @gmail.com account and post a screenshot of the error message if it doesn't work?

**Comment by Nikkau** [comment]
Hum, maybe it's me, I'm misleaded by the error message which say "thoughtbot email" and I forgot my google account use a custom domain and not @gmail.com.

I don't have one to confirm.

**Comment by paulcsmith** [comment]
@Nikkau Ah yes, the error message says "use a thoughtbot email" but it is really looking for an @gmail.com account. Sorry about that. I've created an issue #417 to fix the error message You can sign up for a gmail account if you want to try Constable out though
