### ISSUE TITLE
Creating an announcement without interests causes an error

### ISSUE THREAD

**Issue by tjmw** [thoughtbot/constable#368]
Creating an announcement without any interests results in:

`no function clause matching in String.split/3`

This comes from `extract_interest_names` where we try to split interest names on the `,` character.

**Comment by germsvel** [comment]
@tjmw I'm revisiting some issues and trying to see if they're still around. I can't reproduce this. It seems to work just fine. Mind if I close this?

**Comment by tjmw** [comment]
Sounds fine to me @germsvel :+1: Thanks for looking into it.
