### ISSUE TITLE
Find better way to style/implement managing interests

### ISSUE THREAD

**Issue by BlakeWilliams** [thoughtbot/constable#392]
![screen shot 2016-07-28 at 10 02 48 am](https://cloud.githubusercontent.com/assets/342554/17215318/7f0b041c-54aa-11e6-96d1-183590173fc6.png)

**Comment by mborsare** [comment]
MVP solution for this was merged with: https://github.com/thoughtbot/constable/commit/e0330814dc59998b9a900d985ad4e9bbb4ce37a7
