### ISSUE TITLE
Email Spacing

### ISSUE THREAD

**Issue by alexandra-aas** [thoughtbot/constable#403]
The even spacing between all elements results in a lack of hierarchy and legibility.

In the screenshot below, "Working together..." was posted by Morgane, but because of the even spacing between elements, the two pieces of info don't feel connected.

![img_2103](https://cloud.githubusercontent.com/assets/1214346/17413473/543cf02e-5a4f-11e6-8b50-dacad5097ddd.jpg)

**Comment by mjankowski** [comment]
Resolved by recent digest email changes.
