### ISSUE TITLE
Images not showing up in announcements

### ISSUE THREAD

**Issue by BlakeWilliams** [thoughtbot/constable#409]
When not going through Shubox and linking directly on the following announcement the image url changes and does not display correctly.

https://constable.io/announcements/277

Might be the Elixir markdown parser doing something odd to the URL, but not sure.

**Comment by mjankowski** [comment]
I'm going to mark this closed because URLs should not have spaces, and I think per the markdown spec the "right thing" is actually happening in these cases.
