### ISSUE TITLE
Use the the permitted email domain in the error message when failing to sign up

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/constable#417]
https://github.com/thoughtbot/constable/blob/45e5e8591db15c2ab4adc23acae0f91023bc7a10/web/controllers/auth_controller.ex#L36 this should instead use https://github.com/thoughtbot/constable/blob/45e5e8591db15c2ab4adc23acae0f91023bc7a10/config/config.exs#L27

See #357

**Comment by mjankowski** [comment]
Done here - https://github.com/thoughtbot/constable/commit/ef43c2033cc633affeff92e579835a9796093583
