### ISSUE TITLE
Include the full text of announcements and comments in the digest email

### ISSUE THREAD

**Issue by mjankowski** [thoughtbot/constable#421]
Currently the digest includes the titles of announcements and a count of the comments left ... but does not include the announcement body or comment body text.

My preference would be to have a "kitchen sink" approach in the digest ... send me literally everything that happened on constable in the last day in an email each morning.

**Comment by BlakeWilliams** [comment]
I thought about this the other morning when I woke up and agreed with this. I think this would be nice as an "enhanced" version of the digest.

**Comment by mjankowski** [comment]
I will give someone a personally autographed picture of me if they do this.

**Comment by BlakeWilliams** [comment]
When I reflect back on my life, not completing this task and getting the autographed picture is one of my largest regrets.

**Comment by mjankowski** [comment]
I made that promise almost two years ago and it seems like I'm on the verge of giving this signed picture to myself. I'll share a picture of me receiving the picture for everyone else to enjoy.
