### ISSUE TITLE
Don't search "This week" or "SRS BSNS"

### ISSUE THREAD

**Issue by croaky** [thoughtbot/constable#435]
I've been finding the experience of https://search.thoughtbot.com has been degrading over time as SRS BSNS increasingly takes up the results of various searches.

For example the "right" answer for https://search.thoughtbot.com/?utf8=%E2%9C%93&q=business+card is buried.

Think one thing we can do in Search is make Constable be last in results, or Handbook first, but another improvement would also be to have Constable search no find SRS BSNS results.

Thoughts? @georgebrock @drapergeek

**Comment by drapergeek** [comment]
I agree, that's frustrating.

I think listing the results last is a quick fix but SRS BSNS encourages more and more duplication.

Maybe there should be some way to tag a constable post as not to include it in search?

**Comment by georgebrock** [comment]
I like the idea of excluding certain posts from the constable results. How about an `exclude_topics` parameter on Constable search? That way, `search.thoughtbot.com` could pass `exclude_topics=serious-business`, but `constable.io/search` wouldn't.

**Comment by drapergeek** [comment]
It seems odd that search would know what is important to exclude and what is not.

**Comment by croaky** [comment]
Some kind of parametrized filters on search makes sense to me, and the Search service can set the default filters that make sense for it.

**Comment by BlakeWilliams** [comment]
I'm a fan of adding an `exclude_interests` field so we can ignore specific interests. I may jump on that today.

**Comment by croaky** [comment]
Thanks for the fixes!
