### ISSUE TITLE
[Oauth2] Update Gem

### ISSUE THREAD

**Issue by rileybracken** [thoughtbot/constable#436]
I find when I am learning a new framework / language it helps enormously to have a sample project like this. Thank you so much for open sourcing it.

I ran into a hiccup with Oauth2 and the API changing. I kept on getting a error of `client_secret is missing` when attempting to `get_token`. After reading through the dependencies documentation + releases I discovered that in [v0.7.0](https://github.com/scrogson/oauth2/releases/tag/v0.7.0) a few things have changed. I had to change the `get_token` method [here](https://github.com/thoughtbot/constable/blob/master/web/services/google_strategy.ex#L23) to something like this:

```
def get_token!(redirect_uri, params \\ [], headers \\ [], options \\ []) do
    client(redirect_uri)
    |> put_param(:client_secret, System.get_env("CLIENT_SECRET"))
    |> OAuth2.Client.get_token!(params, headers)
end
```

According to this [comment](https://github.com/scrogson/oauth2/pull/69#issuecomment-251752721):
> The following parameters are what are specified in the OAuth2 spec under section 4.1.3 as required:
>
> - grant_type
> - code
> - redirect_uri
> - client_id

There could be a better way to handle that `put_param`, I am still pretty new to Elixir and that is what I came up with to make it work.

Another thing that has changed is the API for `OAuth2.AccessToken.get!` so 

The code [here](https://github.com/thoughtbot/constable/blob/master/lib/constable.ex#L32) gets changed to this:

```
Pact.put(:request_with_access_token, OAuth2.Client)
```

This isn't super high priority but if anyone runs into the issue while working through the codebase, instead of cloning and running it they could run into this issue.

**Comment by germsvel** [comment]
Thank you for opening this issue @rileybracken! I was just updating OAuth2 and found this very helpful!
