### ISSUE TITLE
Use free SSL option on Heroku?

### ISSUE THREAD

**Issue by odlp** [thoughtbot/constable#437]
I noticed this app still uses the paid Heroku SSL addon. Could it be migrated to the new [free SSL option from Heroku](https://blog.heroku.com/ssl-is-now-included-on-all-paid-dynos)?

Apps:
- constable-api-production
- constable-api-staging
- constable-production

**Comment by tjmw** [comment]
Closing this as it looks like `constable-api-(production|staging)` are now using the free SSL option.

I don't think `constable-production` is used any longer (left over from when the architecture was separate API/front-end apps).
