### ISSUE TITLE
Can't vote answers whose box is too wide

### ISSUE THREAD

**Issue by pablobm** [thoughtbot/constable#442]
Tried on Firefox.

Adding a `<pre>` to a comment will make it wider than the design intended, making the voting interface disappear below the comment box. See example:

![Layout shenanigans](https://cloud.githubusercontent.com/assets/36066/23868388/214f060e-0817-11e7-88e5-76f3a2e78c8a.png)

In the above example, @tysongach's comment is too wide, hiding the voting interface. Compare with @mygulamali's comment right after, which renders correctly.

The screenshot is taken from https://ask.thoughtbot.com/questions/121/is-it-preferred-use-ruby-or-js-detect-browser-support

**Comment by paulcsmith** [comment]
@pablobm I think this was meant for thoughtbot/ask :D I'll go ahead and close this

**Comment by pablobm** [comment]
Argh!
