### ISSUE TITLE
Upgrade to Phoenix 1.3.0

### ISSUE THREAD

**Issue by germsvel** [thoughtbot/constable#450]
We should upgrade constable to use Phoenix 1.3.0. 

A guide for the upgrade can be found [here](http://phoenixframework.org/blog/upgrading-from-120-to-130) and a slightly older version [here](https://gist.github.com/chrismccord/71ab10d433c98b714b75c886eff17357). 

Phoenix v1.3.0 is supposed to be backwards compatible release with v1.2.x., so we could take this in steps. I think following the upgrade guide we could do it in these steps,

- [x] [bump dependency](https://gist.github.com/chrismccord/71ab10d433c98b714b75c886eff17357#bump-your-phoenix-dep) and [update static manifest location](https://gist.github.com/chrismccord/71ab10d433c98b714b75c886eff17357#update-your-static-manifest-location)
- [x] [update project to use new directory structure](https://gist.github.com/chrismccord/71ab10d433c98b714b75c886eff17357#update-your-project-the-new-13-directory-structure-optional)
- [x] [move static assets into `assets` directory](https://gist.github.com/chrismccord/71ab10d433c98b714b75c886eff17357#move-static-assets-inside-self-contained-assets-directory)
- [ ] In step 2, everything in the `web` directory would be moved into `lib/constable_web` which would include models. In this step, we should bring anything that is not a controller, view, or channel out of `lib/constable_web` and into `lib/constable`.

Of the three, I think updating the project to use the new structure will be the biggest change, and even though it's technically optional, I think we should move the project to have the format that phoenix projects will have in the future.

**Comment by germsvel** [comment]
I hadn't closed this issue yet because the last step is not actually finished. That step is technically  not necessary for Phoenix 1.3.0, but I think it makes sense to finish updating the application to be a "standard" Phoenix 1.3 app.

**Comment by mjankowski** [comment]
I opened https://github.com/thoughtbot/constable/pull/526 which I think might complete the last part here...

After those changes, the things left in `constable_web` are:

- The folders for: channels, controllers, templates, views
- controller_helper.ex (should this move?)
- emails.ex (move?)
- endpoint, gettext, router - seems these all stay here in 1.3 projects

**Comment by mjankowski** [comment]
This MIGHT be done now after latest batch of merges.

**Comment by germsvel** [comment]
@mjankowski sorry for taking so long to respond. I do think that with your latest batch of changes, we can call this done. 

I think one last change we _could_ do is to remove the notion of _models_ and introduce something else more in line with Phx 1.3. But I think if/when we want to do that, we could do it in a separate issue. 

So I'll close this for now. Let me know if you prefer to reopen and handle that here.
