### ISSUE TITLE
Filter messages by ones I've commented on

### ISSUE THREAD

**Issue by mborsare** [thoughtbot/constable#461]
When I'm trying to find an old announcement, I want to see only the one's I've commented on. That way I can quickly narrow down my hunt.

**Comment by ThoughtbotThom** [comment]
Not sure if related functionality, but would love to be able to filter one's I'm the author of (or have user pages that show interests and authored posts)

**Comment by germsvel** [comment]
@ThoughtbotThom not sure if this is what you're looking for or if you mean further filtering, but we recently added the posts you've authored under "Your announcements" in the nav bar. 

![your-announcements](https://user-images.githubusercontent.com/3245976/61551824-38343180-aa24-11e9-8154-bf3168350c12.gif)

**Comment by ThoughtbotThom** [comment]
Oh awesome, that is indeed helpful, didn't even see the update!

**Comment by germsvel** [comment]
Sweet. Maybe I should write constable posts about constable updates 😄 . It might be a good idea to update people on what they can (and still cannot) do with constable. 

Please keep the issues and ideas coming. I would like to make this a better tool!

**Comment by ThoughtbotThom** [comment]
Thanks!

**Comment by stratigos** [comment]
I believe this is implemented with #715. Please let me know if anything else is needed to satisfy this issue.
