### ISSUE TITLE
Remove "general" interest

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/constable#491]
> to reduce confusion can we delete the general interest in constable and reassign everything in to  #everyone

**Comment by edwardloveall** [comment]
Agreed. I just had this happen to me. I thought `#general` would post to the general slack channel.

**Comment by mjankowski** [comment]
This is all set. I updated the announcements and users which were connected to "general" (replacing with "everyone" where it was not already there), and then deleted general.
