### ISSUE TITLE
Delete or disable users

### ISSUE THREAD

**Issue by cpytel** [thoughtbot/constable#501]
We have many users still in Constable who are no longer with the company, with no way to delete or disable them.

It would be great to have some way to delete or disable users.

**Comment by germsvel** [comment]
@cpytel not sure if this helps, but looking at the code base there seems to be a way to `deactivate` users by going to `/user_activations`. I don't know if there's a way to get there via the UI, but that might do what you want.

**Comment by cpytel** [comment]
I had no idea this existed. I don't think we need to link it as long as we know it exists, we can make sure its in our off boarding checklist. Thanks!

**Comment by cpytel** [comment]
Unfortunately, I've just deactivated a bunch of people and then to check it I went to draft a new post, chose the everyone topic and all of the people who are deactivated are listed there. I suspect that deactivations don't have an impact on whether the user shows up in who is subscribed to a topic, only whether they can log in?

**Comment by germsvel** [comment]
Yeah, looking a little deeper, it seems like we make sure _not_ to send notifications to deactivated emails but the users still show up in the preview of people who are subscribed to that `interest`. I'll add a PR soon to remove the users from showing up in that list and also make sure they don't show up if someone tries to mention them (via `@name`).

**Comment by cpytel** [comment]
Looks like it did, thanks!
