### ISSUE TITLE
Make it clear how to set an avatar

### ISSUE THREAD

**Issue by edwardloveall** [thoughtbot/constable#504]
If you're not aware of [Gravatar](http://gravatar.com) or its default icon, it's somewhat difficult to figure out how to set an avatar in constable.io

It'd be great to have a link to http://gravatar.com with some explanation about how to set one.

**Comment by germsvel** [comment]
@edwardloveall that's a great point. Do you think a comment with a link in the "Profile and settings" section would do? 

![screen shot 2018-08-24 at 2 48 04 pm](https://user-images.githubusercontent.com/3245976/44602253-0cc1ac00-a7ad-11e8-96e8-02f0ed59035f.png)

**Comment by edwardloveall** [comment]
Yeah that's about what I was picturing. Maybe there's even a help article on gravatar that explains it?

**Comment by germsvel** [comment]
@edwardloveall added a small PR #513 to help alleviate this issue. Not sure that it's a complete solution, but probably a first step in the right direction? I'd love feedback on the copy if you have time.

**Comment by mjankowski** [comment]
I noticed a tiny typo in this area ("...subscribe to me to...") and while I was fixing that I gave the avatar copy another once over:

![screen shot 2018-09-13 at 4 01 55 pm](https://user-images.githubusercontent.com/225/45512699-862a3a00-b76e-11e8-817a-a7315611290b.png)
