### ISSUE TITLE
Images don't have alt tags

### ISSUE THREAD

**Issue by enatario** [thoughtbot/constable#608]
Images should have `alt` tags associated with them.

* Avatars should have an alt tag that says something along the lines of `picture of [person's name]`.

* Images used in a post or in comments should have an alt tag. We use markdown to place images which comes with the ability to add an alt description (`![description of image](imgurl)`) but it does not retain the description as an alt when posted.

**Comment by mjankowski** [comment]
Adding the `alt` tags for avatars is easy enough and I'll do that now.

The issue with stripping things from markdown is that the sanitizer we're using has various modes and I'm struggling to find one which allows both iframes and alt tags at the same time. Will keep looking.

**Comment by enatario** [comment]
Awesome! Thank you for looking into it! 🤗
