### ISSUE TITLE
Not everyone is subscribed to `#everyone`

### ISSUE THREAD

**Issue by ThoughtbotThom** [thoughtbot/constable#637]
Would be nice to be able to accurately message the whole company.
Perhaps auto-subscribe when a new user is added and make #everyone un-unsubscribable

**Comment by lady3bean** [comment]
I have a couple questions that would help me to work on this, as I'm just starting to familiarize myself with the project.

- It looks like new users are already being subscribed to the #everyone interest here in the [auth controller](https://github.com/thoughtbot/constable/blob/a24ee1115c314ffa08482b9a92eef76e5f485920/lib/constable_web/controllers/auth_controller.ex#L121). The other place it looks like users are created is [via the API](https://github.com/thoughtbot/constable/blob/a24ee1115c314ffa08482b9a92eef76e5f485920/lib/constable_web/controllers/api/user_controller.ex#L7), in which case users are not being added to the #everyone interest. So is the work here primarily to do the same thing here as in the auth controller?

- My understanding is that all interests are un-subscribable - so would there need to be a change to make the #everyone interest un-subscribable? Or is there something else you were thinking about for this?

**Comment by mike-burns** [comment]
@lady3bean be sure to see the follow-up in <https://github.com/thoughtbot/handbook/issues/1382>.

**Comment by mike-burns** [comment]
> My understanding is that all interests are un-subscribable - so would there need to be a change to make the #everyone interest un-subscribable?

Absolutely not, please.
