### ISSUE TITLE
Strike-through markdown is inconsistent between preview and final rendering

### ISSUE THREAD

**Issue by georgebrock** [thoughtbot/constable#651]
Strike-through, which is very important for [bad jokes in Constable posts][1] is inconsistent between the preview and the final render.

When previewing an announcement, `~single tildes~` render as strike-through. After an announcement has been published, `~~double tildes~~` are needed.

[1]: https://constable.io/announcements/2174-a-draft-tool-for-developer-skill-self-assessment

**Comment by germsvel** [comment]
@georgebrock might this be related to https://github.com/thoughtbot/constable/issues/638?

**Comment by georgebrock** [comment]
Yep, looks like the same thing! I'll close this and leave a comment on #638 instead.
