### ISSUE TITLE
The PERMITTED_EMAIL_DOMAIN environment variable fails to load

### ISSUE THREAD

**Issue by WilHall** [thoughtbot/constable#654]
Issue previously discussed [here](https://github.com/thoughtbot/constable/pull/603#issuecomment-517829621)

## To reproduce:
Follow the setup instructions in the README, and configure your `.env` file with at least:
```
CLIENT_ID=<STAGING_CLIENT_ID>
CLIENT_SECRET=<STAGING_CLIENT_SECRET>
PERMITTED_EMAIL_DOMAIN=thoughtbot.com
```
Try and log in with your thoughtbot email address, and it will fail with the console error:
```
Email address _ not from permitted _ domain
```

## The issue
Environment variables from the `.env` file are not available in `config.exs`; Inspecting the environment from that file:
```
IO.inspect(System.get_env())
```
does not include any variables from the `.env` file.

**Comment by mjankowski** [comment]
I wonder if there's something machine/OS/version/etc specific about this.

When I run `iex -S mix` and then `System.get_env()` I do see the permitted email domain value in the env vars list (pulled in from my `.env` file).

If relevant:

```
magicvault:constable mjankowski$ mix -v
Erlang/OTP 21 [erts-10.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Mix 1.8.1 (compiled with Erlang/OTP 21)
```

**Comment by WilHall** [comment]
@mjankowski Hmm, interesting.

The environment variables _are_ present when I run `System.get_env()` via `iex -S mix` but _not_ when I run it from `config.exs`. Do you see the same? Or do they also exist for you in the output of `IO.inspect(System.get_env())` from within `config.esx` when running the app?

**Comment by germsvel** [comment]
I'm gonna add one more weird case to this. When @tysongach and I looked at this a while back, `System.get_env("PERMITTED_EMAIL_DOMAIN")` would return the right value. 

But `Application.fetch_env!(:constable, :permitted_email_domain)` (which is set to `System.get_env("PERMITTED_EMAIL_DOMAIN")` in `config/config.exs`) was returning `nil`.

**Comment by WilHall** [comment]
I opened a PR "fixing" this issue in the way recommended by `envy`: https://github.com/thoughtbot/constable/pull/655

I'm not sure if it explains all the discrepancies in behavior we are seeing, but it does fix the issue of accessing the environment from within the config files.
