### ISSUE TITLE
Author info gets squished by “subscribe to thread” button on small screens

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/constable#678]
When viewing an announcement using a device with a small screen, the author’s info (avatar, name, date) gets squished by the “subscribe to thread” button:

![IMG_3336](https://user-images.githubusercontent.com/903327/63856876-a992c880-c970-11e9-8d04-fadd7d3b3270.png)

**Comment by enatario** [comment]
I also noticed that it creates a horizontal overflow scroll on the whole page in some instances

![overflow-scroll](https://user-images.githubusercontent.com/2642348/64734252-434f8f00-d4b4-11e9-8b47-923f14fa329e.gif)
