### ISSUE TITLE
Using Gravatar for avatars

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/constable#683]
We’re currently using [Gravatar](https://en.gravatar.com/) for avatar images. There are two issues I see with that:

1. It means I have to use yet another service to manage a photo of me. Some folks might not even know what Gravatar is, and it’s a bit weird to describe (I think this leads to point 2 below).
1. It’s not uncommon to see this on Constable instead of a colleagues face:

   ![grav](https://user-images.githubusercontent.com/903327/63859436-5a9b6200-c975-11e9-980a-a2408151f0c5.jpg)

I have a hunch that Gravatar is being used because it’s implementation on the dev-side is fairly straightforward.

Would it be possible and/or valuable to leverage the avatars we already have in Hub or Slack?

**Comment by WilHall** [comment]
I agree 💯 that for thoughtbot we should ideally integrate with hub. Did you have thoughts on how that might look alongside an open-source compatible offering (probably Gravatar)?

**Comment by mjankowski** [comment]
I suspect that the lib we are using (ExGravatar) might not support this and we'd have to roll our own or use something else -- but in theory we could leave the hostname portion configurable, and support a "gravatar-style" URL from hub itself, if we care deeply about this.

So our TB instance would hit something like `https://hub.thoughtbot.com/avatars/:md5-email-hash`, but the open source version would default that configuration to stock gravatar urls.

**Comment by WilHall** [comment]
This was fixed by #743
