### ISSUE TITLE
Are the hashtags needed?

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/constable#691]
We use a hashtag (number/pound sign: `#`) in front of “Constable” in the header, as well as in front of interests:

![Screen Shot 2019-08-30 at 13 51 53](https://user-images.githubusercontent.com/903327/64041462-882b0b80-cb2d-11e9-8182-6899019a5d8e.png)

- Are they needed? 
- What’s the purpose?
- Is it to mimic Slack, and/or Twitter?

**Comment by WilHall** [comment]
`#Constable` as a header is really strange. I have always wondered about that.

I personally like having them for the interests because I think it is a good visual indicator of how an interest behaves (e.g. like a label) but this could also be conveyed visually using an icon perhaps? Whatever visual treatment they have, we should also make sure they read well to screen reader users.

**Comment by tysongach** [comment]
On the blog, we have “topics” and they just appear as normal links: https://thoughtbot.com/blog

It feels as though Constable’s “interests” are the same thing as a ”topic” on the blog.

**Comment by tysongach** [comment]
It seems like hashtags are needed/valuable when it’s the user-generated text that houses them, but that’s not (currently) what we’re doing. Meaning, in Twitter, when you put a hashtag in that tweet, it becomes a hyperlink in the published tweet. Slack, you can mention a channel in a message, and that becomes a hyperlink.

But here on Constable, the interest is a discrete field, and we don’t seem to be hyperlinking interests _within_ the body of an announcement.

**Comment by tysongach** [comment]
Now I’m wondering if we just piggy-back off the mental-model of the blog and remove the hashtag, while also renaming Interests to Topics. It reduces the need to understand two different systems when they are structurally equivalent.

**Comment by WilHall** [comment]
I am in favor of renaming interests to topics. I think that naming clarifies what we use them for (for example "boston" is exactly an interest)

**Comment by tysongach** [comment]
Yeah, that’s a great point.

I just realized that we diverge even further with [Ask](https://ask.thoughtbot.com/), which uses “tags” to group content:

![Screen Shot 2019-09-04 at 09 55 23](https://user-images.githubusercontent.com/903327/64261238-3651ff00-cefa-11e9-9770-7e950c68c686.png)

I would think “topics” is a fine way to group content in all three of these places (blog, Constable, Ask). Using a shared language reduces mental overhead.
