### ISSUE TITLE
Update stylelint configuration

### ISSUE THREAD

**Issue by WilHall** [thoughtbot/constable#693]
We should standardize the stylelint configuration using [thoughtbot/stylelint-config](https://github.com/thoughtbot/stylelint-config).

**Comment by tysongach** [comment]
I think we’re already using that?

https://github.com/thoughtbot/constable/blob/113be78d2b74241a1126d6bf4dede6e11acb5c58/assets/.stylelintrc.json#L1-L3

**Comment by WilHall** [comment]
Oh yes, we are. 😅
