### ISSUE TITLE
Hub integration

### ISSUE THREAD

**Issue by WilHall** [thoughtbot/constable#728]
Several open issues (#460, #683) would require Hub integration to resolve.

This issue is for the back-end hub integration, and will simply add a link to the user's profile in Hub to the constable user settings page.

After the Hub integration is in place, future issues can utilize it.

**Comment by tysongach** [comment]
The conversation over in #729 has made me realize that we have a “Your name” field in the user settings. This could also be pulled from Hub, potentially.

**Comment by WilHall** [comment]
@tysongach Great point - I created #733 to track it.
