### ISSUE TITLE
Buggy behavior with usernames that contain a period

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/constable#802]
It appears that usernames that contain periods (and maybe other punctuation?) are not working correctly. 

Here’s a screenshot of a comment I just posted where the username `@conor.devine` is not highlighted at all, and the user `@sarah.dawson` only has `@sarah` highlighted (seemingly because we have another user named `@sarah`):

![Screen Shot 2019-11-05 at 12 31 27](https://user-images.githubusercontent.com/903327/68300447-c97af280-006b-11ea-990a-7507a9e27f1b.png)

The DOM for that comment body is…

```html
<p>
  Thanks, @conor.devine - I’ve updated your Hub schedule, as well as
  <strong>@sarah</strong>.dawson’s and <strong>@elisa</strong>’s.
  John Wu has PTO on Friday, so leaving his schedule at 4 days.
</p>
```

**Comment by germsvel** [comment]
Interesting. Thanks for opening this Tyson! Seems we're doing this with a regex, and it doesn't account for `.` or other punctuation. I imagine we can adjust this without too much of a problem.
