### ISSUE TITLE
Showing multiple entries for multiple comments in a single thread

### ISSUE THREAD

**Issue by ThoughtbotThom** [thoughtbot/constable#804]
To improve scroll-ability, would love if there was only 1 entry for every post one commented on. Since we don't see the comment in this view, showing multiple comments to the same post is redundant.

<img width="565" alt="Screen Shot 2019-11-06 at 2 07 37 PM" src="https://user-images.githubusercontent.com/6619621/68329438-32c82900-009f-11ea-80dc-da5eb14b3be3.png">

**Comment by germsvel** [comment]
@ThoughtbotThom are you seeing this on that new "Your comments" tab? (weird name for it too). Just want to make sure I know how we can reproduce that error.

**Comment by ThoughtbotThom** [comment]
@germsvel sorry, yes this is in the "Your Comments" tab
