### ISSUE TITLE
Can't seem to upload drag and drop images

### ISSUE THREAD

**Issue by germsvel** [thoughtbot/constable#866]
Stephanie reported not being able to upload images. I was able to reproduce that. Dragging and dropping the image simply changes the url of the page, instead of embedding the image. 

![cant-upload-images](https://user-images.githubusercontent.com/3245976/78815486-58cf5d80-799e-11ea-8cf9-df5e0096c8ae.gif)

**Comment by WilHall** [comment]
Based on this console error, it looks like the script from Shubox.io is failing to load:

```
Loading failed for the <script> with source “https://js.shubox.io/v1/d690a45f.js”.
```

Visiting that URL, it looks to be due to a certificate error.

**Comment by mjankowski** [comment]
I sent email to Mr Shubox to ask about invalid cert.

**Comment by mjankowski** [comment]
Mr Shubox got right on this. Cert problem is fixed.
