### ISSUE TITLE
Plug.Conn is imported but not used in router.ex

### ISSUE THREAD

**Issue by sushant12** [thoughtbot/constable#880]
https://github.com/thoughtbot/constable/blob/master/lib/constable_web.ex#L61

I believe that we should remove it if it's not  used.

**Comment by germsvel** [comment]
@sushant12 thanks for opening this issue. Importing `Plug.Conn` in the router is the standard way Phoenix generates apps (you can see that [in the Phoenix template](https://github.com/phoenixframework/phoenix/blob/ea10baae82a9b849b9b4b4c1977dcfc344662863/installer/templates/phx_single/lib/app_name_web.ex#L66) for generating a new phoenix app), so I'm going to close this issue along with the associated PR.
