### ISSUE TITLE
Constable is unusably slow for some users

### ISSUE THREAD

**Issue by georgebrock** [thoughtbot/constable#909]
@eunjeeyoon and @sharplet, and maybe others, have experienced very slow load times.

Here's a screenshot from Eunjee, which shows an initial page load of 0.2s but a completion time of 1.2 minutes.

More discussion in Slack: https://thoughtbot.slack.com/archives/C03HS40ML/p1593725041000500

<img width="554" alt="Screen shot of Chrome network activity on a slow load" src="https://user-images.githubusercontent.com/35861/86411521-0777f700-bc8b-11ea-899b-6c484546d6c0.png">

**Comment by sharplet** [comment]
Here's a snapshot from Safari's network debugger:
<img width="1124" alt="Screen Shot 2020-07-02 at 5 42 19 PM" src="https://user-images.githubusercontent.com/147686/86411850-bddbdc00-bc8b-11ea-87f4-62007c1ec8c8.png">

**Comment by sharplet** [comment]
Note the following metrics: Duration 0ms, **Latency 110.14s**. That shubox URL never loads, and the page eventually pops in when it times out. When I disable JavaScript, the page loads incredibly quickly.

**Comment by sharplet** [comment]
Possibly-related shubox issue: https://github.com/thoughtbot/constable/issues/866

**Comment by sharplet** [comment]
Can we make it so this doesn't block page load?

**Comment by georgebrock** [comment]
We could probably put an `async` or `defer` on this `<script>` element:

https://github.com/thoughtbot/constable/blob/master/lib/constable_web/templates/layout/app.html.eex#L22

We should probably also fix the broken script URL. I also see it failing to load, but for whatever reason it doesn't take so long to fail for me (in Safari or Chrome)

**Comment by sharplet** [comment]
I get the impression from [Shubox's setup documentation for Constable](https://dashboard.shubox.io/domains/constable-io) that their JavaScript is meant to be embedded in our codebase. Perhaps it used to be hosted at shubox.io and that's no longer supported?

**Comment by sharplet** [comment]
FWIW: the slowdown seems like a DNS issue. I'd been playing around with content blockers in Safari to try and disable JavaScript altogether for Constable, and I've noticed that the timeout has disappeared for me. Maybe my DNS cache knows that js.shubox.io is no longer valid?

**Comment by mjankowski** [comment]
I think we are using an old/legacy method of including shubox. Might be worth review.

**Comment by germsvel** [comment]
I'll try to handle this in two separate PRs.

1. Set the `<script>` to `async` -- hopefully that fixes the immediate problem. 
2. Update shubox to be installed [via yarn/npm](https://github.com/shuboxio/shubox.js/blob/master/README.md#with-yarn-or-npm)

**Comment by jayroh** [comment]
@georgebrock @sharplet @germsvel @mjankowski  If y'all every have any performance or usability issues with Shubox, just hit me up. I'd love to help -- always hungry for feedback.

And for what it's worth - the js.shubox.io domain was deprecated last year and removed 4 months ago. I sent an email out to the address on the account to notify of it. Should change it if it never made it y'all.

**Comment by georgebrock** [comment]
@jayroh Thanks! Also, hi!

We had plenty of time to fix it, but I guess either the email address is wrong or whoever saw the email didn't make the connection to needing a Constable change.

I think you already did the right things by allowing plenty of time and sending out an email, but if you wanted to go above and beyond It might have helped us understand the problem if the URL still existed, but responded with e.g. 410 and a short body linking to the deprecation announcement.

**Comment by germsvel** [comment]
Thanks @jayroh! I did end up updating Shubox to no longer use the deprecated js.shubox.io domain in https://github.com/thoughtbot/constable/pull/913. 

And while I was doing so, I really enjoyed discovering these gems:  😂 

![image](https://user-images.githubusercontent.com/3245976/89182241-6323f180-d563-11ea-9521-fa53effe3416.png)

**Comment by jayroh** [comment]
> but if you wanted to go above and beyond It might have helped us understand the problem if the URL still existed, but responded with e.g. 410 and a short body linking to the deprecation announcement.

@georgebrock  - 100%. I should have figured out a way to make this happen at the time. 🤦 

> And while I was doing so, I really enjoyed discovering these gems: 😂

Seeing my own face freaks me out sometimes. So glad I finally got a haircut 😆. 

@germsvel I saw something in a commit about this:

> There are some improvements we could make. In particular, we could add
> an `uploadingTemplate` to shubox to notify the user that we're in the
> process of uploading the image. But we found some difficulty with that
> and we leave that work for the future.

Is there a bug? Anything I can help with?

Thanks, y'all -  all the best to you! 👋

**Comment by germsvel** [comment]
Hi @jayroh thanks for checking in!

> Is there a bug? Anything I can help with?

There is a bug where the `uploadingTemplate` isn't replaced by the `successTemplate`. It's just appended instead. But I wasn't sure if it was coming from Shubox or from how we're storing constable posts in local storage as draft posts. I think I tried both the "append" and "insertAtCursor" `textBehavior`s, but none of them seemed to work. I didn't have enough time at the moment to completely figure it out, and since it might just be how we're storing draft posts, I didn't want to open an issue in Shubox.

**Comment by jayroh** [comment]
All set @germsvel 👍 

v0.5.0 just made its way up to NPM with a fix.
